
services:
  - type: web
    name: poizon-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
